[package]
name = "fpcompressor"
version = "0.1.0"
authors = ["Ivan Tsybulin <uranix@yandex-team.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitstream-io = "1.0.0"
num = "0.4.0"
rand = "0.8.3"